### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by azafred** [okta/okta-jwt-verifier-python#31]
This library is outputting a deprecation warning and very little documentation in a path to move forward.
`/home/fred/.local/lib/python3.9/site-packages/okta_jwt_verifier/jwt_verifier.py:39: DeprecationWarning: JWTVerifier will be deprecated soon. For token verification use IDTokenVerifier or AccessTokenVerifier. For different jwt utils use JWTUtils.`

**Comment by serhiibuniak-okta** [comment]
@azafred, @abhaynayak24 Version 0.2.2 has been released https://github.com/okta/okta-jwt-verifier-python/releases/tag/v0.2.2
I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem still exists.
